"""Exactly reproduce the stationary no-reopening seed-202 run with extra audits.

Default invocation only prints the plan. Pass --execute to train on the original
recorded device, without changing configuration or training source. During the
last 200 optimizer steps, a fixed existing validation set is measured before the
optimizer update and immediately before/after recycling. Nothing measured by
this evaluator is returned to the learner or controller.

The original trusted local checkpoint is read only for final exact comparisons.
No original run files or source files are changed. Output is diagnostic JSON and
Markdown, including any mismatch rather than claiming an exact reproduction.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
import time


ROOT = Path(__file__).resolve().parents[1]
TAIL_STEPS = 200


def read_json(path):
    return json.loads(path.read_text(encoding="utf-8-sig"))


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_hash():
    result = hashlib.sha256()
    for path in sorted((ROOT / "src" / "acp_cl").glob("*.py")):
        result.update(path.name.encode())
        result.update(path.read_bytes())
    return result.hexdigest()


def make_plan(run_dir: Path) -> tuple[dict, dict]:
    result = read_json(run_dir / "result.json")
    config = result["config"]
    if result["method"] != "acp_v2_no_reopening" or result["seed"] != 202:
        raise ValueError("this diagnostic is fixed to acp_v2_no_reopening seed202")
    if config["data"].get("dataset") != "procedural_shapes" or config["data"].get("regime") != "stationary":
        raise ValueError("the original stationary procedural-shapes run is required")
    if config.get("eval_split", "validation") != "validation":
        raise ValueError("this diagnostic requires the original validation split")
    config_sha256 = hashlib.sha256(json.dumps(config, sort_keys=True).encode()).hexdigest()
    if config_sha256 != result["config_sha256"]:
        raise ValueError("stored configuration hash mismatch")
    if source_hash() != result["source_sha256"]:
        raise ValueError("current training source does not match the completed run")
    checkpoint = run_dir / "checkpoint.pt"
    if not checkpoint.is_file():
        raise ValueError("the original trusted local checkpoint is required")
    total_steps = result["allocation_summary"]["steps"]
    if total_steps != config["data"]["n_experiences"] * config["steps_per_experience"]:
        raise ValueError("recorded training horizon disagrees with configuration")
    return result, {
        "method": result["method"], "seed": result["seed"],
        "original_run": str(run_dir.resolve()),
        "config_sha256": result["config_sha256"], "source_sha256": result["source_sha256"],
        "execution_device": result["execution_device"],
        "original_result_sha256": digest(run_dir / "result.json"),
        "original_checkpoint_sha256": digest(checkpoint),
        "audit_script_sha256": digest(Path(__file__)),
        "first_audited_step": max(1, total_steps-TAIL_STEPS+1), "last_audited_step": total_steps,
        "fixed_validation_set": "unchanged last-experience validation set, reused for every audit measurement",
        "measurements": ["before optimizer update", "after optimizer, immediately before recycling",
                         "immediately after recycling; unchanged value reused when no unit was reset"],
        "information_flow": "evaluator-only; no measurements returned to learner, replay, controller, or optimizer",
        "comparison": "bitwise equality against every final model-state tensor in the original trusted checkpoint",
    }


def run_audit(run_dir: Path, result: dict, plan: dict) -> dict:
    # Import only after the user explicitly chooses execution. Plan-only checks
    # do not initialize a model or touch the GPU.
    sys.path.insert(0, str(ROOT / "src"))
    import numpy as np
    import torch
    from torch.nn import functional as F
    from acp_cl.data import build_stream, preprocess
    from acp_cl.experiment import new_learner, resolve_device, seed_everything, train_experience

    config, seed, method = result["config"], result["seed"], result["method"]
    if torch.__version__ != result["environment"]["torch"] or np.__version__ != result["environment"]["numpy"]:
        raise ValueError("Torch/NumPy versions differ from the original run")
    device = resolve_device(result["execution_device"])
    if device.type == "cuda" and torch.cuda.get_device_name(device) != result["environment"]["gpu"]:
        raise ValueError("GPU model differs from the original run")
    # This file was generated by the same local project; loading is deliberately
    # restricted to its original completed checkpoint, never an arbitrary upload.
    original = torch.load(run_dir / "checkpoint.pt", map_location="cpu", weights_only=False)
    for key in ("config_sha256", "source_sha256", "method", "seed", "execution_device"):
        if original.get(key) != result.get(key):
            raise ValueError(f"checkpoint {key} differs from the completed result")
    if original["completed"] != config["data"]["n_experiences"]:
        raise ValueError("original checkpoint is not the completed run")
    seed_everything(seed, int(config.get("threads", 4)))
    stream = build_stream(config["data"], seed)
    learner = new_learner(config, stream, method, seed, device)
    fixed = stream.experiences[-1].validation
    fixed_x = preprocess(fixed.tensors[0].to(device), learner.dataset)
    fixed_y = fixed.tensors[1].to(device)
    audit_records = []
    pending = {}
    evaluator_calls = 0
    cuda_devices = [device.index if device.index is not None else torch.cuda.current_device()] if device.type == "cuda" else []

    def measure():
        nonlocal evaluator_calls
        modes = [(module, module.training) for module in learner.model.modules()]
        try:
            learner.model.eval()
            # Evaluation is deterministic here; also preserve global Torch RNGs
            # explicitly so this hook cannot consume the training RNG stream.
            with torch.random.fork_rng(devices=cuda_devices), torch.inference_mode():
                logits = learner.model(fixed_x)
                accuracy = float((logits.argmax(1) == fixed_y).float().mean())
                cross_entropy = float(F.cross_entropy(logits, fixed_y))
            evaluator_calls += 1
            return {"accuracy": accuracy, "cross_entropy": cross_entropy}
        finally:
            for module, training in modes:
                module.training = training

    engine_step = learner.engine.step
    engine_recycle = learner.engine.recycle

    def audited_step(*args, **kwargs):
        step = learner.step_number
        if step >= plan["first_audited_step"]:
            pending[step] = {"step": step, "before_update": measure()}
        update = engine_step(*args, **kwargs)
        if step in pending:
            pending[step]["optimizer_diagnostics"] = dict(update)
        return update

    def audited_recycle(*args, **kwargs):
        step = learner.step_number
        if step < plan["first_audited_step"]:
            return engine_recycle(*args, **kwargs)
        before = measure()
        recycling = engine_recycle(*args, **kwargs)
        after = measure() if recycling["recycled"] else dict(before)
        row = pending.pop(step)
        row.update({
            "before_recycle": before, "after_recycle": after,
            "post_recycle_forward_performed": bool(recycling["recycled"]),
            "recycled": recycling["recycled"], "recycled_by_population": recycling["recycled_by_population"],
            "update_accuracy_change_pp": 100 * (before["accuracy"]-row["before_update"]["accuracy"]),
            "update_ce_change": before["cross_entropy"]-row["before_update"]["cross_entropy"],
            "reset_accuracy_change_pp": 100 * (after["accuracy"]-before["accuracy"]),
            "reset_ce_change": after["cross_entropy"]-before["cross_entropy"],
        })
        audit_records.append(row)
        return recycling

    learner.engine.step = audited_step
    learner.engine.recycle = audited_recycle
    start = time.perf_counter()
    curves = []
    for index, experience in enumerate(stream.experiences):
        curves.append(train_experience(learner, experience, config, seed))
        full_evaluation = (index+1) % config.get("retention_eval_every_experiences", 1) == 0 or index == len(stream.experiences)-1
        for previous in range(index if full_evaluation else 0):
            learner.accuracy(getattr(stream.experiences[previous], config.get("eval_split", "validation")))
        if (index+1) % config.get("progress_every_experiences", 1) == 0 or index == len(stream.experiences)-1:
            print(f"reset-damage audit: experience {index+1}/{len(stream.experiences)}, step {learner.step_number}", flush=True)
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    if source_hash() != plan["source_sha256"]:
        raise ValueError("training source changed during reproduction")
    if len(audit_records) != TAIL_STEPS or pending:
        raise ValueError("audit did not observe exactly the planned last 200 updates")
    model_state = learner.model.state_dict()
    expected_model = original["learner"]["model"]
    mismatches = []
    if model_state.keys() != expected_model.keys():
        mismatches.append({"name": "model keys", "detail": "state dictionaries have different keys"})
    for name in model_state.keys() & expected_model.keys():
        current, expected = model_state[name].detach().cpu(), expected_model[name].cpu()
        if not torch.equal(current, expected):
            mismatches.append({"name": name, "max_absolute_difference": float((current-expected).abs().max())})
    expected_allocation = read_json(run_dir / "allocation.json")["trace"]
    original_events = {row["step"]: row for row in read_json(run_dir / "events.json")["events"]}
    for row in audit_records:
        event = original_events.get(row["step"])
        if event is not None:
            row["original_paired_replay_damage"] = event.get("monitor", {}).get("paired_replay_damage")
            row["original_probe_loss_before"] = event.get("monitor", {}).get("probe_loss_before")
            row["original_probe_loss_after"] = event.get("monitor", {}).get("probe_loss_after")
    verification = {
        "final_model_tensors_exact": not mismatches,
        "model_tensor_count": len(model_state), "model_mismatches": mismatches,
        "allocation_trace_exact": learner.allocation_trace == expected_allocation,
        "recorded_learning_curves_exact": curves == [list(map(tuple, curve)) for curve in result["learning_curves"]],
        "training_cost_counters_exact": learner.cost == original["learner"]["cost"],
        "controller_state_exact": learner.controller.state_dict() == original["learner"]["controller"],
    }
    exact = all(verification[key] for key in (
        "final_model_tensors_exact", "allocation_trace_exact", "recorded_learning_curves_exact",
        "training_cost_counters_exact", "controller_state_exact",
    ))
    resets = [row for row in audit_records if row["recycled"]]
    return {
        "plan": plan,
        "status": "exact reproduction verified" if exact else "reproduction mismatch; inspect verification before interpreting",
        "verification": verification,
        "evaluation": {"experience_index": len(stream.experiences)-1, "examples": len(fixed_y),
                       "split": "validation", "fixed_set_reused": True,
                       "forward_calls": evaluator_calls, "extra_examples": evaluator_calls*len(fixed_y)},
        "summary": {"audited_steps": len(audit_records), "reset_events": len(resets),
                    "reset_units": sum(row["recycled"] for row in resets),
                    "largest_reset_accuracy_drop_pp": min([row["reset_accuracy_change_pp"] for row in resets], default=0),
                    "largest_update_accuracy_drop_pp": min(row["update_accuracy_change_pp"] for row in audit_records),
                    "largest_reset_ce_increase": max([row["reset_ce_change"] for row in resets], default=0),
                    "largest_update_ce_increase": max(row["update_ce_change"] for row in audit_records)},
        "interpretation": [
            "Within-step differences isolate the immediate reset effect on one fixed validation sample, conditional on the observed training trajectory.",
            "They do not identify the effect of removing earlier resets, newborn gain, momentum, or consolidation over the whole training run.",
            "The selected anomaly and audit window are post-hoc diagnostics. No hyperparameters, learning rules, or feedback paths were changed.",
            "Wall time includes additional validation and concurrent GPU workloads; it is not a matched-compute measurement.",
        ],
        "wall_seconds": time.perf_counter()-start, "records": audit_records,
    }


def markdown(audit: dict) -> str:
    check = audit["verification"]
    lines = ["# Stationary seed-202 reset audit", "", f"Status: **{audit['status']}**.", "",
             f"Final model: {check['model_tensor_count']} tensors; exact match: **{check['final_model_tensors_exact']}**. "
             f"Allocation trace, original acquisition curves, cost counters, and controller state checks: "
             f"{check['allocation_trace_exact']}, {check['recorded_learning_curves_exact']}, "
             f"{check['training_cost_counters_exact']}, {check['controller_state_exact']}.", "",
             f"The fixed evaluator uses all {audit['evaluation']['examples']} examples from the original final-experience validation set. "
             "It observes steps 1801-2000 without returning measurements to the learner.", "",
             "| Step | Units reset | Accuracy before update (%) | Before reset (%) | After reset (%) | Update change (pp) | Reset change (pp) | Reset CE change |",
             "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for row in audit["records"]:
        if row["recycled"] or row["step"] >= 1965:
            lines.append(f"| {row['step']} | {row['recycled']} | {100*row['before_update']['accuracy']:.2f} | "
                         f"{100*row['before_recycle']['accuracy']:.2f} | {100*row['after_recycle']['accuracy']:.2f} | "
                         f"{row['update_accuracy_change_pp']:+.2f} | {row['reset_accuracy_change_pp']:+.2f} | "
                         f"{row['reset_ce_change']:+.6f} |")
    lines.extend(["", "All 200 per-step records and exact-verification details are preserved in `instrumented_audit.json`.", ""])
    lines.extend(f"- {point}" for point in audit["interpretation"])
    lines.extend(["", f"Original training source SHA-256: `{audit['plan']['source_sha256']}`.", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run-dir", type=Path, default=ROOT / "runs/v2_shapes_stationary/acp_v2_no_reopening_seed202")
    parser.add_argument("--output", type=Path, default=ROOT / "runs/reset_damage_audit")
    parser.add_argument("--execute", action="store_true", help="Run the instrumented reproduction on the original recorded device")
    args = parser.parse_args()
    try:
        result, plan = make_plan(args.run_dir.resolve())
        if not args.execute:
            print(json.dumps({"status": "plan only; no training started", **plan}, indent=2))
            return
        if args.output.resolve() == args.run_dir.resolve():
            raise ValueError("audit output must differ from the original run directory")
        audit = run_audit(args.run_dir.resolve(), result, plan)
        args.output.mkdir(parents=True, exist_ok=True)
        (args.output / "instrumented_audit.json").write_text(json.dumps(audit, indent=2, allow_nan=False)+"\n", encoding="utf-8")
        (args.output / "instrumented_audit.md").write_text(markdown(audit), encoding="utf-8")
        print(f"{audit['status']}: {args.output.resolve()}", flush=True)
        if audit["status"] != "exact reproduction verified":
            raise SystemExit(1)
    except (ValueError, OSError, KeyError) as error:
        parser.exit(2, f"Cannot audit: {error}\n")


if __name__ == "__main__":
    main()
